basic.forever(function () {
    TobbieII.forward()
    basic.pause(3000)
    TobbieII.stopwalk()
    basic.pause(3000)
    TobbieII.rightward()
    basic.pause(800)
    TobbieII.stopturn()
    basic.pause(1000)
})
